// Unique AppID of a project, which is of the Number type. You can obtain it in ZEGOCLOUD Admin Console.
export const appID = "YOUR_APPID";

// Access server address, which is of the String type. You can obtain it in ZEGOCLOUD Admin Console. (For more information about how to obtain it, see Prerequisites.)
export const server = "YOUR_SERVER_ADDRESS";

// The value of `token` is generated by your server. To quickly perform debugging, you can apply for a temporary audio and video token of the String type in ZEGOCLOUD Admin Console (https://console.zego.im/).
export const token = "YOUR_TOKEN";

// You can set `userID` based on your service requirements but ensure that it is globally unique.
export const userID = "YOUR_USER_ID";

// You can set `userName` based on your service requirements, which is not necessarily to be unique.
export const userName = "YOUR_USER_NAME";

// You can set `roomID` based on your service requirements but ensure that it is globally unique.
export const roomID = "YOUR_ROOM_ID";

export default { appID, server, token, userID, userName, roomID };
